FROM nvcr.io/nvidia/tritonserver:23.10-py3

# For production, build and copy your model repository into /models.
COPY triton_models /models

EXPOSE 8000 8001 8002
CMD ["tritonserver", "--model-repository=/models"]
